#!/bin/sh
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_AMAZON_FASHION.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Arts_Crafts_and_Sewing.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Automotive.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Books.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_CDs_and_Vinyl.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Cell_Phones_and_Accessories.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Clothing_Shoes_and_Jewelry.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Digital_Music.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Electronics.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Grocery_and_Gourmet_Food.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Home_and_Kitchen.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Industrial_and_Scientific.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Kindle_Store.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Movies_and_TV.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Office_Products.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Patio_Lawn_and_Garden.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Pet_Supplies.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Sports_and_Outdoors.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Tools_and_Home_Improvement.json.gz --no-check-certificate
wget -P /data/liufengyuan/NLPinFinance/Data https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Toys_and_Games.json.gz --no-check-certificate